
VENTANA_X = 1200
VENTANA_Y = 480

COMIENZO_X = 200
COMIENZO_Y = 300

FPS = 60
GRAVEDAD_Y = 1
ALTURA_SALTO = 17
VELOCIDAD_X = 5 
VELOCIDAD_Y = ALTURA_SALTO
CANT_FRAME_CORRER = 2
LARGO_SUPERFICIE = 1200
ANCHO_SUPERFICIE = 10
INTERVALO_INCREMENTO = 4000
INCREMENTO_VELOCIDAD = 0.5

COMIENZO_OBSTACULO_X = 1300

COMIENZO_PAJARO_BAJO_Y =275
COMIENZO_PAJARO_ALTO_Y =250


COMIENZO_CACTUS_GRANDE_Y =290
ANCHO_CACTUS_GRANDE = 60
ALTO_CACTUS_GRANDE = 90
ANCHO_CACTUS_GRANDE_HITBOX = 45
ALTO_CACTUS_GRANDE_HITBOX = 60


COMIENZO_CACTUS_CHICO_Y =290
ANCHO_CACTUS_CHICO = 40
ALTO_CACTUS_CHICO = 80
ANCHO_CACTUS_CHICO_HITBOX = 35
ALTO_CACTUS_CHICO_HITBOX = 35


COMIENZO_CACTUS_GRANDE_DOBLE_Y =290
ANCHO_CACTUS_GRANDE_DOBLE = 70
ALTO_CACTUS_GRANDE_DOBLE = 90
ANCHO_CACTUS_GRANDE_DOBLE_HITBOX = 45
ALTO_CACTUS_GRANDE_DOBLE_HITBOX = 55

COMIENZO_SUPERFICE_X = VENTANA_X/2
COMIENZO_SUPERFICE_Y = COMIENZO_Y+27


ANCHO_DINOSAURIO = 48
ALTO_DINOSAURIO = 64
ANCHO_DINOSAURIO_AGACHADO = 60
ALTO_DINOSAURIO_AGACHADO = 64
ANCHO_DINOSAURIO_HITBOX_SUP = 30
ALTO_DINOSAURIO_HITBOX_SUP = 30
ANCHO_DINOSAURIO_HITBOX_INF = 32
ALTO_DINOSAURIO_HITBOX_INF = 27

TAMAÑO_FUENTE_CONTADOR = 40
POSICION_CONTADOR_X = VENTANA_X-150
POSICION_CONTADOR_Y = 20

